### ISSUE TITLE
能否接受添加ms_toollib作为依赖项

### ISSUE THREAD

**Issue by eee555** [hgraceb/web-minesweeper-player#11]
想做一个pr来支持evf格式。不想重复写逻辑了，想用ms_toollib做解析。最后打包完体积会增加370k。是否可以接受

**Comment by hgraceb** [comment]
无法接受，本项目有独立的解析规则：[BaseVideo.ts](https://github.com/hgraceb/flop-player/blob/098f385b3b2465994a6469d49323433fb713f718/src/game/BaseVideo.ts)

**Comment by eee555** [comment]
我会尽量适配已有的代码，不做破坏性修改

**Comment by eee555** [comment]
export class EVFVideo extends BaseVideo这样，就改这个文件，以及少量配置

**Comment by hgraceb** [comment]
成本是每个用户都要多下 1/3 大小的数据，收益只是省了一次重写和少量维护的时间，个人认为没有性价比可言。

如果是想合并到雷网可以在雷网的编程群中收集其他人的意见，如果只是自用则可以独立维护一份下游代码。

**Comment by eee555** [comment]
js换成wasm，这种架构就是为了减少重写，不论日后如何更新都可以保证在所有地方都是一致的。要不是当时是同时开发的，其他格式录像的解析逻辑也应该用这个模块的才对。再考虑一下吧，我不想搞得太分裂。

**Comment by eee555** [comment]
新开个branch可以吧？

**Comment by hgraceb** [comment]
感觉没有必要，单独的分支最后还是要维护，而且也不会合并到雷网，想不到有什么好处，要自用的话完全可以 fork 一份维护。
